Question Bank : https://drive.google.com/file/d/1KMvOueR-cQxRJD9cADGccJxVmYDp2xkV/view

<b>Q.1 Write a Python Program to Add Two Matrices?

In [7]:
import numpy as np

def add_matrix(mat1, mat2):
    
    try:
        return mat1+mat2
    except Exception as e:
        return e
    

In [25]:
a = np.random.rand(2,5)
b= np.random.rand(2,5)
add_matrix(a,b)

array([[1.47039748, 0.34182021, 1.29525453, 1.02547726, 1.1387961 ],
       [1.15490795, 0.78928951, 0.4313865 , 0.93124609, 0.94337301]])

<b>Q.2 Write a Python Program to Multiply Two Matrices?

In [26]:
def multiply_matrix(mat1, mat2):
    try:
        return np.multiply(mat1,mat2)
    except Exception as e:
        return e

In [27]:
multiply_matrix(a,b)

array([[0.52594609, 0.00925987, 0.36037936, 0.26208129, 0.2881954 ],
       [0.33340523, 0.03344881, 0.03914287, 0.17666311, 0.21498591]])

<b>Q.3 Write a Python Program to Transpose a Matrix?

In [28]:
def transpose_matrix(mat):
    try:
        return np.transpose(mat)
    except Exception as e:
        return e

In [29]:
transpose_matrix(multiply_matrix(a,b))

array([[0.52594609, 0.33340523],
       [0.00925987, 0.03344881],
       [0.36037936, 0.03914287],
       [0.26208129, 0.17666311],
       [0.2881954 , 0.21498591]])

<b>Q.4 Write a Python Program to Sort Words in Alphabetic Order?

In [32]:
def sort_words(sentence):
    try:
        return sorted(sentence.lower().split(" "))
    except Exception as e:
        return e

In [33]:
sort_words("This is a planet")

['a', 'is', 'planet', 'this']

<b>Q.5 Write a Python Program to Remove Punctuation From a String?

In [70]:
import string

def remove_punctuation(sentence):
    try:
        for i in sentence:
            if i in string.punctuation:
                sentence = sentence.replace(i,"")
        return sentence        
    except Exception as e:
        return e

In [71]:
remove_punctuation("This is $%& world,")

'This is  world'